/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class game_GameEngine */

#ifndef _Included_game_GameEngine
#define _Included_game_GameEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     game_GameEngine
 * Method:    initGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_game_GameEngine_initGame
  (JNIEnv *, jobject);

/*
 * Class:     game_GameEngine
 * Method:    placeMarker
 * Signature: (IIC)Z
 */
JNIEXPORT jboolean JNICALL Java_game_GameEngine_placeMarker
  (JNIEnv *, jobject, jint, jint, jchar);

/*
 * Class:     game_GameEngine
 * Method:    checkWinner
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_game_GameEngine_checkWinner
  (JNIEnv *, jobject);

/*
 * Class:     game_GameEngine
 * Method:    getCell
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_game_GameEngine_getCell
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     game_GameEngine
 * Method:    resetGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_game_GameEngine_resetGame
  (JNIEnv *, jobject);

/*
 * Class:     game_GameEngine
 * Method:    isGameOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_game_GameEngine_isGameOver
  (JNIEnv *, jobject);

/*
 * Class:     game_GameEngine
 * Method:    countMoves
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_game_GameEngine_countMoves
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
